name: Trigger METplus Workflow

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'

jobs:
  trigger_metplus:
    name: Trigger METplus testing workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub values for reference
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.METPLUS_BOT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dtcenter',
              repo: 'METplus',
              workflow_id: 'testing.yml',
              ref: 'develop',
              inputs: {
                repository: '${{ github.repository }}',
                ref: '${{ github.ref }}',
                actor: '${{ github.actor }}',
                sha: '${{ github.sha }}',
                pusher_email: '${{ github.event.pusher.email }}'
              },
            });
